Document Fixes
usc-cisco/scientia pull request #2
Opened 2024-08-18 12:09 UTC by 0-BSCode

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Problem Context

Explain the **details** for making this change. What existing problem does the pull request solve?

- Typo in README where **repository** was spelled as **repostiory**
- Request to change filename to leave out name of owner

## Solution

Explain how you addressed the Problem Context outlined previously.

- Fixed typo
- Edited filename

## Closing Issues

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2024-08-18 13:08 UTC, Luzefiru commented
Is there any particular reason author is omitted from the file names?

I initially added them because we might run into similar reviewer titles, so the name sort of acted like a unique identifier together with the full file name.

We're in dire need of a naming convention for files so that they don't conflict with each other.

Do you have any suggestions for that, @0-BSCode?

2024-08-18 13:10 UTC, 0-BSCode commented
It was mentioned by Sab and Wayne to remove the name of the author from the file (not sure why). Maybe we can use USC ID instead? Wdyt @Luzefiru

2024-08-18 13:43 UTC, thesabrinahyap commented
Hello! It's not about removing the name of the author but instead, change the title of the folders. It was cis 1102 but should be 1201. Thanks!

2024-08-18 13:46 UTC, Luzefiru commented
> It was mentioned by Sab and Wayne to remove the name of the author from the file (not sure why). 
I clarified with Sab, and she said that the issue was that there was files with CIS1102 instead of CIS1201. She's fine with having name attribution on the files.

Maybe we can use USC ID instead? Wdyt @Luzefiru
> If authors don't like attribution to keep the material anonymous or etc, we'd better not use USC ID since that defeats the purpose.

I'm thinking we can follow the format `YYYYMMDD-slug-of-header`, where
- `YYYYMMDD` is the time the note/file is created.
- `slug-of-header` is the first heading or title found in the file uploaded.

What do you think?

2024-08-18 13:46 UTC, 0-BSCode commented
ohh I see. I'll make the changes

2024-08-18 22:54 UTC, 0-BSCode commented
@Luzefiru let's just keep the names as is for now with the student name being like the unique identifier. Some files don't indicate when they were created

2024-08-19 00:06 UTC, Luzefiru requested changes
LGTM except 1 typo. I'll merge once it's resolved. Thank you, Bry!

2024-08-19 00:06 UTC, Luzefiru commented on docs/courses/cis1201/resources/index.md
> +- [Wayne Dayata's CIS12021 Finals Mock Exam, part 1](./files/wayne-cis1201-final-mock-exam-test1.pdf) and then [Wayne's CIS1102 Finals Mock Exam, part 2](./files/wayne-cis1201-final-mock-exam-test2.p
Please change `CIS12021` to `CIS1202`.

2024-08-19 00:24 UTC, 0-BSCode commented on docs/courses/cis1201/resources/index.md
> +- [Wayne Dayata's CIS12021 Finals Mock Exam, part 1](./files/wayne-cis1201-final-mock-exam-test1.pdf) and then [Wayne's CIS1102 Finals Mock Exam, part 2](./files/wayne-cis1201-final-mock-exam-test2.p
Oops. Nice catch!

2024-08-19 00:26 UTC, Luzefiru approved these changes

2024-08-19 00:26 UTC, merged